Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '${DB_DATABASE}'
        user: '${DB_USER}'
        password: '${DB_PASS}'
        host: '${DB_HOST}'
  Imagine:
    driver: '${IMAGINE_DRIVER}'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true