Neos:
  Flow:
    persistence:
      backendOptions:
        driver: ${DB_DRIVER}
        charset: '${DB_CHARSET}'
        dbname: '${DB_DATABASE}'
        user: '${DB_USER}'
        password: '${DB_PASS}'
        host: '${DB_HOST}'
        port: '${DB_PORT}'
  Imagine:
    driver: '${IMAGINE_DRIVER}'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true